version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build: ./backend
    networks:
      - app-network

  database:
    build: ./database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

